### ISSUE TITLE
Errors in user input cause loss of data.

### ISSUE THREAD

**Issue by AnrDaemon** [ngx/pbin#11]
When a user submits an unacceptable paste, such a minimal issue shouldn't cause complete void of user's input.
Make character replacements, if you wish, and show an edited form with accompanying error message back to user. If user is fine with proposed edits, he/she can resubmit the form, or edit further to achieve desired results.

**Comment by MTecknology** [comment]
I'm used to pressing `Alt + Left_Arrow` when I reach an error page where my input is now gone and almost always expect what I previously input to still be there. I /want/ an error page to be hit so I'm not sure what I can do for this. Any ideas?

**Comment by MTecknology** [comment]
Now that the captcha is in place and it's proven effective at eliminating spam, I think we have a lot more flexibility. On both invalid input, or no input at all, we can easily take the submission and store it somewhere else with a link returned (or redirect--depending on source--might add an extra form field for that..) pointing to a special link to confirm that one entry. We would obviously be not returning /any/ of the submitted data in the approval form to prevent circumventing this step.

... any thoughts? wanna help write it? :D
