### ISSUE TITLE
User submitted characters are replaced with html entities in raw view

### ISSUE THREAD

**Issue by tomoshizuki** [ngx/pbin#12]
Some user submitted special characters in pastes are translated to their respective html entities, which is good. In the default html-view characters generally look fine. 

However, when the "raw" button is clicked the literal representations of the html code are shown as well which isn't expected as the raw view of a paste must show the exact, unaltered user input.

**Examples:**

```
" translates to &#34;
' translates to &#39;
& translates to &amp;
> translates to &gt;
< translates to &lt;
```

There may be more cases. Those are the ones I'm aware of.

**Comment by MTecknology** [comment]
I seem to remember doing that to prevent xss. Something better is needed.

**Comment by AnrDaemon** [comment]
When you return Content-Type: text/plain, it should not be processed by the browser scripting, thus safe on that side.

**Comment by MTecknology** [comment]
Thanks for submitting this and sorry for the delay. We finished a "tiny" update and believe this is now resolved on the current source. This is now running live at http://p.ngx.cc/. Feel free to review!

**Comment by AnrDaemon** [comment]
Seems all right now, thanks!
