### ISSUE TITLE
[Bug] Mollom module problems

### ISSUE THREAD

**Issue by teward** [ngx/pbin#7]
In the current implementation of this pastebin application, there is functionality in the application to allow Mollom anti-spam.  This application calls upon `import Mollom` and `Mollom.MollomAPI(` as such.

Unfortunately, with the current iteration of `Mollom` available from the PyPI libraries (or `pip install mollom`), there is one easily-fixable problem, and one much more critical problem:

 1. **[Minor]** `import Mollom` on Ubuntu Python 2.7 (in Trusty 14.04), and likely in other instances, will fail, whereas `import mollom` seems to work and import the module.
 2. **[Critical]** The `Mollom.MollomAPI( ... )` function is nonexistent in the `mollom` libraries.  As such, if `check_spam` is set to `True` in the configuration, you will run into errors stating that the function does not exist in the module.  (`README` has been updated as a result of #6 to mark `check_spam` as `False`, which mitigates this issue partially if the app is run with the default config options.)

**Comment by MTecknology** [comment]
Should mollom stuff just be ripped out? We're not using it anyway...

**Comment by teward** [comment]
If we don't use it, then perhaps it should be removed.

**Comment by MTecknology** [comment]
I just removed it in the latest commit.
